### ISSUE TITLE
does highlight work?

### ISSUE THREAD

**Issue by dbarrosop** [eonpatapon/tree-sitter-cue#5]
Hello,
thanks for writing this plugin, I have a question, I installed this tree-sitter plugin following your instructions but highlighting doesn't seem to work, according to `TSModuleInfo`:

```
>> default       autotag  context_commentstring  highlight  incremental_selection  indent  rainbow
...
cue              ✗        ✗                      ✗          ✓                      ✗       ✗
...

>> textobjects   lsp_interop  move  select  swap
...
cue              ✗            ✗     ✗       ✗
...
```

Thanks!

**Comment by eonpatapon** [comment]
Yes that's normal I think, it will only install the parser. The highlighting queries which are provided in `./queries/highlights.scm` have to be copied in your nvim config.

In a directory `after/queries/cue/`.

Let me know if that works and I will update the documentation.

**Comment by eonpatapon** [comment]
More precisely: https://github.com/nvim-treesitter/nvim-treesitter#adding-queries

**Comment by dbarrosop** [comment]
Awesome, that did the trick, might be worth mentioning in the howto or even adding this plugin to [nvim-treesitter/nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter).

Thanks a lot for the quick help and for this grammar :)
